// Problem Description
// Given a string s containing only digits (0-9) and an integer b (0 ≤ b ≤ 9), you can perform a rotation operation any number of times.
// A rotation operation takes the last b characters of the string and moves them to the front.
// For example:

// If s = "3456" and b = 1, one rotation gives "6345"
// If you rotate again, it becomes "5634"

// Your task is to return the total number of unique numbers that can be generated by performing the rotation operation any number of times (including zero times).

// Examples
// Example 1:
// Input: s = "123456", b = 1
// Output: 6
// Explanation:
// Possible rotations by b=1:
// - 0 rotations: "123456"
// - 1 rotation:  "612345"
// - 2 rotations: "561234"
// - 3 rotations: "456123"
// - 4 rotations: "345612"
// - 5 rotations: "234561"
// - 6 rotations: "123456" (cycles back to original)

// Total unique numbers: 6
// Example 2:
// Input: s = "54321", b = 2
// Output: 4
// Explanation:
// Possible rotations by b=2:
// - 0 rotations: "54321"
// - 1 rotation:  "21543"
// - 2 rotations: "43215"
// - 3 rotations: "15432"
// - 4 rotations: "32154"
// - 5 rotations: "54321" (cycles back)

// Total unique numbers: 4
// Example 3:
// Input: s = "132", b = 1
// Output: 3
// Explanation:
// Possible rotations by b=1:
// - 0 rotations: "132"
// - 1 rotation:  "213"
// - 2 rotations: "321"
// - 3 rotations: "132" (cycles back)

// Total unique numbers: 3
// Example 4:
// Input: s = "1111", b = 1
// Output: 1
// Explanation:
// All rotations produce "1111", so only 1 unique number.
// Example 5:
// Input: s = "123", b = 0
// Output: 1
// Explanation:
// b=0 means no rotation is possible, so only the original "123" exists.

// Constraints

// 1 <= s.length <= 10^5
// s consists of digits only ('0' to '9')
// 0 <= b <= 9

function solution(s: string, b: number): number {
  if (s.length === 0 || b === 0) return 0;

  let current = s;
  const numbers = new Set();

  for (let x = 0; x < s.length; x++) {
    numbers.add(current);

    current = current.slice(-b) + current.slice(0, -b);

    if (current === s) {
      break;
    }
  }

  return numbers.size;
}

console.log(solution('1234', 1)); // output: 4
console.log(solution('123456', 1)); // output: 6
console.log(solution('223456', 2)); // output: 3
console.log(solution('111111', 2)); // output: 1
console.log(solution('111011', 2)); // output:
